### PR TITLE
[GH-11] gopath and gobin

### PR DESCRIPTION
**Pull request by 030**

### CODE REVIEW

**Comment by andrewrothstein** [comment]
First off, thanks for taking the time to use and give feedback on the role.

I've tried to split the "installation" vs "configuration" into the andrewrothstein.go and andrewrothstein.go-dev roles, respectively. This PR seems to indicate that perhaps I've done a poor job at separating the two or that there's not a lot of use in this approach.

What are your thoughts?

**Comment by 030** [comment]
Hi, Thanks for the reply. If the configuration is restricted to this repository then I would advocate to merge it, but if the go-dev is used in other roles then it could be kept as is and then a dependency could be added to this role.

What do you think about that? If the go-dev is used by other roles then I could apply the changes in go-dev and add a dependency to this repository.

**Comment by Kaurin** [comment]
My comment is somewhat unrelated to your discussion, but I have two pet peeves:

1. Please quote the vars: `export MYVAR="${whatever} space space"`
1. I feel that `${GOBIN}` should go before `${PATH}`  to combat system golang installations: `export PATH="${GOBIN}:${PATH}"`

**Comment by 030** [comment]
@Kaurin and @andrewrothstein thanks for the comments. I think that this can be closed as go modules solved the issue.

**Pull request closed without merging**
